{% set name = "yaqd-acton" %}
{% set version = "2022.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 14839914a855b15681cd29aa8ff0744dff3d6e5f81d9a364a81a1d61ba39021c

build:
  number: 0
  noarch: python
  entry_points:
    - yaqd-acton-2150i = yaqd_acton._acton_2150i:Acton2150I.main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - flit
    - pyserial
    - yaqd-core >=2021.3.0
  run:
    - python >=3.8
    - pyserial
    - yaqd-core >=2021.3.0

test:
  imports:
    - yaqd_acton
  commands:
    - pip check
    - yaqd-acton-2150i --help
  requires:
    - pip

about:
  home: https://gitlab.com/yaq/yaqd-acton
  summary: yaq daemons for Acton Research Corporation instruments
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - untzag
    - ksunden
